// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credentials.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCredentials = `-- name: CreateCredentials :one
INSERT INTO credentials (id, username, email, password)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password
`

type CreateCredentialsParams struct {
	ID       uuid.UUID
	Username string
	Email    string
	Password string
}

func (q *Queries) CreateCredentials(ctx context.Context, arg CreateCredentialsParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredentials,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}
