// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: friendship.sql

package database

import (
	"context"
)

const getFriends = `-- name: GetFriends :many
SELECT u.id, u.name, u.email, u."emailVerified", u.image, u."createdAt", u."updatedAt" FROM "user" u JOIN friendship f ON u.id = f.user_id
WHERE u.id = $1
`

func (q *Queries) GetFriends(ctx context.Context, id string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getFriends, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
