// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type FriendRequestStatus string

const (
	FriendRequestStatusACCEPTED FriendRequestStatus = "ACCEPTED"
	FriendRequestStatusREJECTED FriendRequestStatus = "REJECTED"
	FriendRequestStatusPENDING  FriendRequestStatus = "PENDING"
)

func (e *FriendRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendRequestStatus(s)
	case string:
		*e = FriendRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendRequestStatus: %T", src)
	}
	return nil
}

type NullFriendRequestStatus struct {
	FriendRequestStatus FriendRequestStatus
	Valid               bool // Valid is true if FriendRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendRequestStatus), nil
}

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           sql.NullString
	RefreshToken          sql.NullString
	IdToken               sql.NullString
	AccessTokenExpiresAt  sql.NullTime
	RefreshTokenExpiresAt sql.NullTime
	Scope                 sql.NullString
	Password              sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Friendship struct {
	ID            uuid.UUID
	UserID        string
	FriendID      string
	RequestStatus FriendRequestStatus
}

type Session struct {
	ID        string
	ExpiresAt time.Time
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	IpAddress sql.NullString
	UserAgent sql.NullString
	UserId    string
}

type User struct {
	ID            string
	Name          string
	Email         string
	EmailVerified bool
	Image         sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
