// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type FriendRequestStatus string

const (
	FriendRequestStatusACCEPTED FriendRequestStatus = "ACCEPTED"
	FriendRequestStatusREJECTED FriendRequestStatus = "REJECTED"
	FriendRequestStatusPENDING  FriendRequestStatus = "PENDING"
)

func (e *FriendRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendRequestStatus(s)
	case string:
		*e = FriendRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendRequestStatus: %T", src)
	}
	return nil
}

type NullFriendRequestStatus struct {
	FriendRequestStatus FriendRequestStatus
	Valid               bool // Valid is true if FriendRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendRequestStatus), nil
}

type Account struct {
	ID                    string
	AccountId             string
	ProviderId            string
	UserId                string
	AccessToken           sql.NullString
	RefreshToken          sql.NullString
	IdToken               sql.NullString
	AccessTokenExpiresAt  sql.NullTime
	RefreshTokenExpiresAt sql.NullTime
	Scope                 sql.NullString
	Password              sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type ConfigOption struct {
	ID            int64
	MenuItemID    sql.NullInt64
	MaxSelectable int32
	Name          string
}

type Friendship struct {
	ID            uuid.UUID
	UserID        string
	FriendID      string
	RequestStatus FriendRequestStatus
}

type Jwk struct {
	ID         string
	PublicKey  string
	PrivateKey string
	CreatedAt  time.Time
}

type MenuItem struct {
	ID      int64
	StoreID sql.NullInt32
	Name    string
	Price   float64
}

type Option struct {
	ID             int64
	ConfigOptionID sql.NullInt64
	Name           string
	PriceDelta     float64
}

type QrCode struct {
	ID      int64
	StoreID sql.NullInt32
	TableNo int32
	Url     string
}

type Session struct {
	ID             string
	ExpiresAt      time.Time
	Token          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IpAddress      sql.NullString
	UserAgent      sql.NullString
	UserId         string
	ImpersonatedBy sql.NullString
}

type Store struct {
	ID     int32
	Name   string
	Tables int32
}

type TwoFactor struct {
	ID          string
	Secret      string
	BackupCodes string
	UserId      string
}

type User struct {
	ID                  string
	Name                string
	Email               string
	EmailVerified       bool
	Image               sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Role                sql.NullString
	Banned              sql.NullBool
	BanReason           sql.NullString
	BanExpires          sql.NullTime
	PhoneNumber         sql.NullString
	PhoneNumberVerified sql.NullBool
	TwoFactorEnabled    sql.NullBool
}

type Verification struct {
	ID         string
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
