-- +goose Up
CREATE TABLE menu_item (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    "store_id" INT,
    FOREIGN KEY ("store_id") REFERENCES stores("id") ON DELETE CASCADE,
    "name" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL
);

CREATE TABLE config_option (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    "menu_item_id" BIGINT,
    FOREIGN KEY ("menu_item_id")  REFERENCES menu_item("id") ON DELETE CASCADE,
    "max_selectable" INT NOT NULL,
    "name" TEXT NOT NULL
);

CREATE TABLE option (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    "config_option_id" BIGINT,
    "name" TEXT NOT NULL,
    "price_delta" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    FOREIGN KEY ("config_option_id") REFERENCES config_option("id") ON DELETE CASCADE
);

-- +goose Down

DROP TABLE option;
DROP TABLE config_option;
DROP TABLE menu_item;